kind: pipeline
name: jsql-ci

steps:
- name: checkstyle
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  commands:
  - mvn validate -B
  when:
    event:
    - push

- name: test common
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -Dtest=CommonTestSuite
  when:
    event:
    - push

- name: test mariadb
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=mariadb -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test mysql
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=mysql -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test oracle
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=oracle -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test db2
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=db2 -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test h2
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=h2 -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test cubrid
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=cubrid -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test postgresql
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=postgresql -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test derby
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=derby -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test sqlite
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=sqlite -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: test sqlserver
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: icuter_home
    path: /home/icuter/
  commands:
  - export ICUTER_HOME=/home/icuter/
  - mvn test -B -Dcheckstyle.skip=true -DdbType=sqlserver -Dtest=DBTypeTestSuite
  when:
    event:
    - push

- name: release
  image: maven:3-jdk-8
  volumes:
  - name: maven
    path: /root/.m2
  - name: gnupg
    path: /root/.gnupg/
  commands:
  - mvn deploy -P release -DskipTests=true -Dcheckstyle.skip=true
  when:
    event:
    - tag

volumes:
- name: maven
  host:
    path: /root/.m2
- name: gnupg
  host:
    path: /root/.gnupg/
- name: icuter_home
  host:
    path: /home/icuter/